### PR TITLE
Add a front page for search

### PR DESCRIPTION
**Pull request by khandelwal**
This adds in a front-page to the whole search effort. This allows us to put some explanatory text under a document search box. 

Currently, I have placeholder text. This will surely change over time.

### CODE REVIEW

**Comment by khandelwal** [comment]
screen shot 2015-02-18 at 5 33 28 pm

**Comment by khandelwal** [comment]
@rjmajma Even though this has placeholder text. It'll likely be there for a short while, and during initial demos. If you want to suggest some changes - now's the time.

**Comment by khandelwal** [comment]
New copy change: 

screen shot 2015-02-18 at 6 48 27 pm

**Comment by rjmajma** [comment]
Merged!

**Pull request merged**
