### PR TITLE
adding Vagrant

### PR DESCRIPTION
**Pull request by geramirez**
Setting up vagrant.

### CODE REVIEW

**Comment by khandelwal** [comment]
There are hundreds of files here that are changing. Can you explain why that is?

**Comment by geramirez** [comment]
All of these files are going into a subdirectory of the Vagrant directory so they autosync. After reading the Vagrant documentation again, there might be a way to sync a directory of choice, but I'll have to teak at it a bit.

**Comment by khandelwal** [comment]
I think the Vagrant related things might need to be in another repo. That's not directly related to this code.

**Comment by khandelwal** [comment]
Let's not change where the code is - based on some weird Vagrant thing.

**Pull request closed without merging**
