### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by geramirez**
upstream merge, and removed small search from krang + contacts updater.

### CODE REVIEW

**Comment by khandelwal** [comment]
It feels like this is not the right solution to the small search thing. Maybe we should just change both searches to use the same parameter and eliminate the problem? Small search can be changed easier than Krang. 

You can also do this 'translation' in the view for ES search. There's a way to use a view, do some work, and then pass it on to the actual haystack view that does the work.

**Comment by ramirezg** [comment]
Yeah, it's possible. We'll just have to redefine the following functions in both forms and views. I'll work on this tomorrow. 
https://github.com/django-haystack/django-haystack/blob/master/haystack/views.py#L74
https://github.com/django-haystack/django-haystack/blob/master/haystack/forms.py#L51
https://github.com/django-haystack/django-haystack/blob/master/haystack/forms.py#L65

**Comment by ramirezg** [comment]
I tried to build a custom faceted search but the usage of `q` is too embedded in haystack. I used [this](https://github.com/projectkrang/foia-hub/pull/15/files#diff-8801747ad02dfc8e6130369d10e0b4b4R76) instead.

**Comment by ramirezg** [comment]
Implemented @shawnbot 's suggestion for [turning off typeahead](https://github.com/projectkrang/foia-hub/blob/60b9710b2ce699c44521cd9ba915ff75193a28e3/foia_hub/templates/base.html#L46) in Krang.

**Comment by ramirezg** [comment]
note to self, just need to add small search to learn and about.

**Pull request merged**
